name: engine
version: 0.0.1-dev.1
description: A framework for building modular applications
homepage: https://engine.dev
repository: https://github.com/ml-it/engine

environment:
  sdk: ">=2.9.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.3.0
  test: ^1.3.4